### ISSUE TITLE
How to get a HS image for a random RGB image not from the dataset?

### ISSUE THREAD

**Issue by ManuBN786** [KAIST-VCLAB/deepcassi#4]
Dear Author,

Thanks for making your brilliant work publicly available.

I just want to know how I can generate a HS image for a random RGB image?

In the code one of the rigid requirement is to mention the path of Ground Truth (GT) image for the particular RGB image.

Please let me know how to get a HS image for a random RGB image without a corresponding GT image.

Thanks in advance

**Comment by inchangchoi** [comment]
Hi ManuBN787,

We don't generate a HS image from an RGB image. If you look into the code carefully, you will notice that the path for Ground Truth is actually the path for 'a Ground Truth HS image'. We take this path, because we generate a compressive input from the ground truth HS image by simulating the image formation of our compressive hyperspectral imager.

Thank you for your inquiry.
